### ISSUE TITLE
cannot load such file -- sequel/extensions/seed (LoadError)

### ISSUE THREAD

**Issue by gffcoutinho** [earaujoassis/sequel-seed#23]
Hi,

I'm getting an error when requiring the extension (require 'sequel/extensions/seed').

I noticed that seed.rb is not present in sequel 5.46.0, ruby version 3.0.2.

I temporarily resolved it by copying https://raw.githubusercontent.com/earaujoassis/sequel-seed/master/lib/sequel/extensions/seed.rb into the gem extensions folder.

**Comment by earaujoassis** [comment]
Hi, @gffcoutinho. You need to *gem-install* `sequel-seed` extension in order to have that file available. Considering your comment, the mentioned file is not available in `sequel`; you must install `sequel-seed` alongside `sequel`. Please double check if you have performed these instructions and let me know if have any other issue. Thanks.

**Comment by earaujoassis** [comment]
Further instructions provided; closing this issue.
